apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello
  annotations:
    werf.io/weight: 100
spec:
  selector:
    matchLabels:
      app: hello
  template:
    metadata:
      labels:
        app: hello
    spec:
      containers:
      - image: nginxdemos/hello:plain-text
        name: demonginx
