apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello
  annotations:
    werf.io/weight: "100"
    werf.io/deploy-dependency-migrations: state=ready,kind=Job,name=waitforme
spec:
  selector:
    matchLabels:
      app: hello
  template:
    metadata:
      labels:
        app: hello
    spec:
      containers:
      - image: {{ $.Values.imageTags.nginx }}
        name: demonginx
