apiVersion: apps/v1
kind: Deployment
metadata:
  name: vault
  annotations:
    werf.io/weight: "10"
spec:
  selector:
    matchLabels:
      app: vault
  template:
    metadata:
      labels:
        app: vault
    spec:
      containers:
      - image: hashicorp/vault:1.19
        name: vault
        env:
          - name: SKIP_SETCAP
            value: "true"
