apiVersion: batch/v1
kind: Job
metadata:
  name: waitforme
  annotations:
    werf.io/deploy-dependency-migrations: state=ready,kind=Deployment,name=vault
spec:
  template:
    spec:
      containers:
      - name: provision
        image: ubuntu:latest
        command: ["sleep",  "3"]
      restartPolicy: Never
  backoffLimit: 4

